import { Injectable } from '@angular/core';
import { Profession } from './profession';
import { ProfessionFull } from './profession-full';
import { Race } from './race';
import { EdgeProviderService } from './edge-provider.service';
import { Edge } from './edge';
import { Hindrance } from './hindrance';
import * as Chance from 'chance';
import { ProfessionFull2 } from './profession-full-2';
import { pickValidEdges } from '@utility/pick-valid-edges';

// tslint:disable: max-line-length

@Injectable({
  providedIn: 'root'
})
export class ProfessionProviderService {

  constructor(
    private readonly edgeProvider: EdgeProviderService
  ) { }

  public get fiftyFathoms(): ProfessionFull2[] {
    const atani = new Race(
      "Atani",
      "Tall, thin, glider-folk with wing-like membranes stretching from their arms.",
      [ new Edge("Agile", "", "Start with d6 Agility"),
        new Edge("Gliders", "", "Can glide. Have skill Flying(ag) at d6. Descend 1\" vertical for every 2\" horizontal. Success on Flying (per round) allows staying level or going up 1\" but sacrificing 2\" horizontal") ],
      [ new Hindrance("Weak", 0, "Hollow bones make you frail. It costs 2 points/advances to raise strength."),
        new Hindrance("No Magic", 0, "This race cannot speak to the elemental spirits")]
    );

    const makeHuman = () => new Race(
      "Human",
      "Humans are versatile and so get an extra edge.",
      [],
      [],
      (rng, r, e, h) => { r.edges.push(...pickValidEdges(rng, r, e, h, this.edgeProvider.fiftyFathomsSwade, 1)); }
    );

    const makeMasaquani = () => new Race(
      "Masaquani",
      null,
      [],
      [],
      (rng, r, _, __) => {
        const skill = rng.pickone(["Agility", "Smarts", "Spirit", "Strength", "Vigor"]);
        r.edges.push(new Edge(`Improved Stat (${skill})`, "", "Masaquani are iconic humanoids. They start with a stat at d6 and embody it."));
      }
    );

    const doreen = new Race(
      "Doreen",
      "Dolphin-folk. Hunted to near extinction by Kehana. At one time there were around 300.",
      [ new Edge("Sea Hunter", "", "Doreen are consummate hunters and know a great deal about the seas they swim. They add +2 to Stealth & Survival rolls made while underwater."),
        new Edge("Semi-Aquatic", "", "Start with d6 in swimming. Move at skill level in inches while swimming. Can stay underwater for 15 minutes before making fatigue rolls.")],
      [ new Hindrance("Racial Enemy (Kehana)", 0, "Doreen hate the kehana and suffer -4 to Charisma when working with them."),
        new Hindrance("No Magic", 0, "This race cannot speak to the elemental spirits")]
    );

    const grael = new Race(
      "Grael",
      "Walrus-folk with some martial tendencies. They name themselves.",
      [ new Edge("Blubber", "", "Gain +1 Toughness (natural armor). +4 to Fatigue rolls to resist cold. -2 to Fatigue rolls in extreme heat."),
        new Edge("Size+1", "", "They chonk. +1 Toughness. Cannot use goods not specifically made for them."),
        new Edge("Strong", "", "Start with d8 strength. May advance strength to d12+2."),
        new Edge("Semi-Aquatic", "", "Start with d6 in swimming. Move at skill level in inches while swimming. Can stay underwater for 15 minutes before making fatigue rolls.")],
      [ new Hindrance("All Thumbs", 0, "–2 to use mechanical or electrical devices.", [""]),
        new Hindrance("Dumb", 0, "Grael aren't deep thinkers. It costs 2 points/advances to raise smarts."),
        new Hindrance("Slow", 0, "Base pace 4 on dry land"),
        new Hindrance("No Magic", 0, "This race cannot speak to the elemental spirits")]
    );

    const kehana = new Race(
      "Kehana",
      "Piranha folk? Underwater pack hunters. They have burbling names that sound unpronouncable to others.",
      [ new Edge("Teeth and Claws", "", "Str+d4 claws/teeth."),
        new Edge("Aquatic", "", "Move at full swimming skill. No drowning. May speak underwater.")],
      [ new Hindrance("Dehydration", 0, "Must immerse themselves in water 1 hour per 24, or take fatigue until incapacitated, then die."),
        new Hindrance("Unwholesome Apetite", 0, "They prefer to consume their food live. -2 to Charisma among non-kehana."),
        new Hindrance("Racial Enemy (Doreen)", 0, "Kehana hunt the weak 'grey-folk' (doreen) relentlessly and inflict grotesque tortures upon them. Suffer -4 to Charisma when working with them."),
        new Hindrance("No Magic", 0, "This race cannot speak to the elemental spirits")]
    );

    const kraken = new Race(
      "Kraken",
      "Squid-looking humanoids. Like Mindflayers. Magical.",
      [ new Edge("Natural Talent", "", "Gain 10 power points. If you do not have arcana, this does nothing."),
        new Edge("Aquatic", "", "Move at full swimming skill. No drowning. May speak underwater.")],
      [ new Hindrance("Dehydration", 0, "Must immerse themselves in water 1 hour per 24, or take fatigue until incapacitated, then die.")]
    );

    const redMan = new Race(
      "(Half-ugak) Red Man",
      "The Red Men of Torath-Ka are basically red Orcs. This is basically a red half-orc.",
      [ new Edge("Strong", "", "Start with d6 strength"),
        new Edge("Tough", "", "Start with a d6 vigor"),
        new Edge("Tough as Nails", "L, V d8", "The hero can take four Wounds before being Incapacitated.")],
      [ new Hindrance("All Thumbs", 0, "–2 to use mechanical or electrical devices."),
        new Hindrance('Clueless', 0, '–1 to Common Knowledge and Notice rolls.'),
        new Hindrance("Dumb", 0, "Half-ugak brains are less developed than most. It costs 2 points/advances to raise smarts."),
        new Hindrance("Outsider", 0, "Universally reviled or at least shunned by other races. -2 to Charisma"),
        new Hindrance("No Magic", 0, "This race cannot speak to the elemental spirits")]
    );

    const scurrilian = new Race(
      "Scurillian",
      "It's a giant crab, created by magic. Pincers. Smart. Great eyes. They molt.",
      [ new Edge("Pincers", "", "Str+d6. They're giant. Treat the two pincers as a separate creature for turns. They're ambidextrous. +2 to Grappling"),
        new Edge("Keen Mind", "", "Their brains are wired to remember details and easily deal with mathematics. +2 to Common Knowledge on relevant rolls."),
        new Edge("Shell", "", "Torso: +3 toughness. Legs: +1 toughness. Does not stack with other armor (if you can even get fitted)"),
        new Edge("Telescopic Eyes", "", "+2 to Notice Rolls to detect things behind them. Can peer over cover with little exposure. -8 penalty to target an eye. 2 damage destroys the eye for 6 months (and shakes)"),
      ],
      [ new Hindrance('Mean', 0, '–1 to Persuasion rolls.') ]
    );

    return [
      new ProfessionFull2("Common Folk", makeHuman(), ["Dagger", "Potato"], "50f", "#"),
      new ProfessionFull2("Common Folk", atani, ["Axe", "Potato"], "50f", "#"),
      new ProfessionFull2("Common Folk", doreen, ["Bone Knife (as dagger)", "Potato"], "50f", "#"),
      new ProfessionFull2("Common Folk", grael, ["Battle Ball", "Potato"], "50f", "#"),
      new ProfessionFull2("Common Folk", kehana, ["Dagger", "Potato"], "50f", "#"),
      new ProfessionFull2("Common Folk", redMan, ["Dagger", "Potato"], "50f", "#"),
      new ProfessionFull2("Common Folk", scurrilian, [], "50f", "#"),
      new ProfessionFull2("Common Folk", makeMasaquani(), [], "50f", "#"),
    ];
  }

  public get swadeDccProfessions(): ProfessionFull[] {
    return [
      new ProfessionFull('Acolyte', 'Human', 'Mace', 'Prayer beads', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Alchemist', 'Human', 'Staff', 'Oil, 1 flask', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Apothecary', 'Human', 'Hardwood Pestle (as club)', 'Strange chemicals, 1 lb.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Animal trainer', 'Human', 'Club', 'Pony', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Armorer', 'Human', 'Hammer (as club)', 'Iron helmet', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Astrologer', 'Human', 'Dagger', 'Spyglass', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Barber', 'Human', 'Razor (as dagger)', 'Scissors', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Bawd', 'Human', 'Dagger', 'Fancy hat', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Beadle', 'Human', 'Staff', 'Holy symbol', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Beekeeper', 'Human', 'Staff', 'Jar of honey', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Blacksmith', 'Human', 'Hammer (as club)', 'Steel tongs', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Blacksmith', 'Human', 'Hammer (as club)', 'Steel tongs', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Brewer', 'Human', 'Wood Mallet (as club)', 'Small barrel of beer', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Brewer', 'Human', 'Wood Mallet (as club)', 'Small barrel of beer', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Burglar', 'Human', 'Dagger', 'Grappling hook', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Butcher', 'Human', 'Cleaver (as axe)', 'Side of beef', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Caravan guard', 'Human', 'Short sword', 'Linen, 1 yard', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Charcoalburner', 'Human', 'Axe', 'Sack of charcoal', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Cheesemaker', 'Human', 'Cudgel (as staff)', 'Stinky cheese', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Chimneysweep', 'Human', 'Pole (as staff)', 'Large broom', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Coachman', 'Human', 'Crossbow', 'Wide-brimmed hat', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Cobbler', 'Human', 'Awl (as dagger)', 'Shoehorn', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Confidence artist', 'Human', 'Dagger', 'Quality cloak', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Cooper', 'Human', 'Crowbar (as club)', 'Barrel', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Costermonger', 'Human', 'Knife (as dagger)', 'Sack of fruit', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Counterfeiter', 'Human', 'Club', '60 lead coins painted silver', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Courier', 'Human', 'Dagger', 'Messages (1d3)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Cultist', 'Human', 'Wavy knife (as dagger)', 'Book of forbidden lore', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Cutpurse', 'Human', 'Dagger', 'Small chest', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Ditch digger', 'Human', 'Shovel (as staff)', 'Fine dirt, 1 lb.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Executioner', 'Human', 'Axe', 'Leather hood', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Farmer*', 'Human', 'Pitchfork (as spear)', 'Hen**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Farmer*', 'Human', 'Pitchfork (as spear)', 'Hen**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Farmer*', 'Human', 'Pitchfork (as spear)', 'Hen**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Farmer*', 'Human', 'Pitchfork (as spear)', 'Hen**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Ferryman', 'Human', 'Long pole (as staff)', '60 copper pieces', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Fisherman', 'Human', 'Club', 'Net', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Fishmonger', 'Human', 'Cleaver (as axe)', 'Salted fish, dozen', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Forester', 'Human', 'Bow', 'Leather armor', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Fortune-teller', 'Human', 'Dagger', 'Tarot deck', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Gambler', 'Human', 'Dagger', 'Dice', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Goliard', 'Human', 'Dagger', 'Bottle of cheap wine', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Gongfarmer', 'Human', 'Trowel (as dagger)', 'Sack of night soil', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Grave digger', 'Human', 'Shovel (as staff)', 'Trowel', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Grave robber', 'Human', 'Shovel (as staff)', 'Lantern', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Guide', 'Human', 'Staff', 'Map', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Guild beggar', 'Human', 'Sling', 'Crutches', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Hayward', 'Human', 'Staff', 'Horn', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Healer', 'Human', 'Club', 'Healing salve, 1 dose (heals 1 hp)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Hedge Wizard', 'Human', 'Dagger', 'Hexdoll', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Herbalist', 'Human', 'Knife (as Dagger)', 'Herbs, 1 lb', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Herder', 'Human', 'Staff', 'Herding dog**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Herder', 'Human', 'Staff', 'Herding dog**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Hermit', 'Human', 'Staff', 'Carved holy symbol', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Hunter', 'Human', 'Bow, short', 'Antlers', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Hunter', 'Human', 'Bow, short', 'Antlers', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Indentured servant', 'Human', 'Staff', 'Locket', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Jester', 'Human', 'Dart', 'Silk clothes', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Jeweler', 'Human', 'Dagger', 'Gem worth 20 gp', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Juggler', 'Human', 'Dagger', 'Ceramic spheres, 3', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Keeper of the hounds', 'Human', 'Spear', 'Dog', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Lightbearer', 'Human', 'Torch (as club)', 'Lantern', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Locksmith', 'Human', 'Dagger', 'Fine tools', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Mendicant', 'Human', 'Staff', 'Holy water, 1 vial', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Mercenary', 'Human', 'Longsword', 'Hide armor', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Merchant', 'Human', 'Dagger', '4 gp, 14 sp, 27 cp', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Midwife', 'Human', 'Knife (as dagger)', 'Blanket, wool', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Miller', 'Human', 'Club', 'Flour, 1 lb.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Miner', 'Human', 'Pick (as spear)', 'Candle, 10', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Minstrel', 'Human', 'Dagger', 'Ukulele', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Minstrel', 'Human', 'Dagger', 'Ukulele', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Molecatcher', 'Human', 'Sharpened staff (as spear)', 'Mole-skin hat', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Mudlark', 'Human', 'Club', 'Lucky copper piece', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Mummer', 'Human', 'Mace prop (as club)', 'Make-up kit', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Nightwatchman', 'Human', 'Spear', 'Black cloak', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Noble', 'Human', 'Longsword', 'Gold ring worth 10 gp', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Ostler', 'Human', 'Staff', 'Bridle', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Outlaw', 'Human', 'Short sword', 'Leather armor', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Porter', 'Human', 'Dagger', 'Bottles of thick beer, 4', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Prospector', 'Human', 'Spear', 'Copper pan', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Prostitute', 'Human', 'Dagger', 'Red cloak', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Rake', 'Human', 'Longsword', 'Lady’s kerchief', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Rope maker', 'Human', 'Knife (as dagger)', 'Rope, 100’', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Sailor', 'Human', 'Belaying Pin (as club)', 'Bottle of rotgut', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Sailor', 'Human', 'Belaying Pin (as club)', 'Bottle of rotgut', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Scribe', 'Human', 'Dart', 'Parchment, 10 sheets', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Servingwench', 'Human', 'Knife (as dagger)', 'Metal serving tray (as shield)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Sewerjack', 'Human', 'Spear', 'Tall leather boots', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Shaman', 'Human', 'Mace', 'Herbs, 1 lb.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Slave', 'Human', 'Club', 'Strange-looking rock', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Smuggler', 'Human', 'Sling', 'Waterproof sack', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Soldier', 'Human', 'Spear', 'Shield', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Soldier', 'Human', 'Spear', 'Shield', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Squire', 'Human', 'Longsword', 'Steel helmet', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Street magician', 'Human', 'Fake ‘Staff of Power’ (as staff)', 'A fluffy white bunny', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Tax collector', 'Human', 'Longsword', '100 cp', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Taxidermist', 'Human', 'Long Needle (as dagger)', 'Stuffed small creature @', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Teamster', 'Human', 'Club', 'Short whip', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Thug', 'Human', 'Brass knuckles (as club)', 'Collection of a dozen teeth', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Tinker', 'Human', 'Hammer', 'Iron pan', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Torturer', 'Human', 'Iron poker (as club)', 'Rope, 50’', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Town crier', 'Human', 'Cudgel (as staff)', 'Horn', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Trapper', 'Human', 'Sling', 'Badger pelt', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Undertaker', 'Human', 'Razor (as dagger)', 'Tall black hat', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('University student', 'Human', 'Dagger', 'Thin book of notes', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Urchin', 'Human', 'Stick (as club)', 'Begging bowl', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Vagabond', 'Human', 'Walking stick (as staff)', 'Pet rock', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Wainwright', 'Human', 'Club', 'Pushcart***', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Weaver', 'Human', 'Dagger', 'Fine suit of clothes', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Wizard’s apprentice', 'Human', 'Dagger', 'Black grimoire', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Woodcutter', 'Human', 'Handaxe', 'Bundle of wood', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Woodcutter', 'Human', 'Handaxe', 'Bundle of wood', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Alchemist', 'Dwarf', 'Staff', 'Oil, 1 flask', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Apothecary', 'Dwarf', 'Cudgel (as staff)', 'Steel vial', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Armorer', 'Dwarf', 'Hammer (as club)', 'Iron helmet', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Beardgroomer', 'Dwarf', 'Razor (as dagger)', 'Scissors', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Beekeeper', 'Dwarf', 'Staff', 'Jar of honey', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Blacksmith', 'Dwarf', 'Hammer (as club)', 'Mithril, 1 oz.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Blacksmith', 'Dwarf', 'Hammer (as club)', 'Mithril, 1 oz.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Brewer', 'Dwarf', 'Wood Mallet (as club)', 'Stein', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Bureaucrat', 'Dwarf', 'Staff of office (as staff)', 'Wax candles (3) and seal', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Butcher', 'Dwarf', 'Cleaver (as axe)', 'Side of beef', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Chest-maker', 'Dwarf', 'Hammer (as club)', 'Wood, 10 lbs.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Chimneysweep', 'Dwarf', 'Pole (as staff)', 'Large broom', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Coaler', 'Dwarf', 'Shovel (as club)', 'Sack with coal', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Counterfeiter', 'Dwarf', 'Dagger', '60 lead coins painted gold', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Dirgesinger', 'Dwarf', 'Dagger', 'Book of dirges', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Engineer apprentice', 'Dwarf', 'Large protractor (as club)', 'Book of mathematical formulae', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Forgeguard', 'Dwarf', 'Axe', 'Iron helmet', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Gatewarden', 'Dwarf', 'Spear', 'Large brass key', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Herder', 'Dwarf', 'Staff', 'Sow**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Jeweler', 'Dwarf', 'Chisel (as dagger)', 'Fine tools', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Lightbearer', 'Dwarf', 'Torch (as club)', 'Lantern', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Locksmith', 'Dwarf', 'Dagger', 'Ring full of keys', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Lorekeeper', 'Dwarf', 'Staff', 'Lorekeeper certification scroll', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Merchant', 'Dwarf', 'Dagger', 'Iron ingots', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Mercenary', 'Dwarf', 'Axe', 'Leather armor', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Miner', 'Dwarf', 'Mattock (as axe)', 'Lantern', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Miner', 'Dwarf', 'Mattock (as axe)', 'Lantern', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Moneylender', 'Dwarf', 'Sack of 380 cp (as club)', 'Ledger', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Mushroom-farmer', 'Dwarf', 'Shovel (as club)', 'Sack', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Outcast', 'Dwarf', 'Club', 'Bottle of elven wine', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Prospector', 'Dwarf', 'Axe', 'Gold nugget worth 7 gp', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Ratcatcher', 'Dwarf', 'Club', 'Net', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Runecaster', 'Dwarf', 'Stave (as club)', 'Rune tiles, 10', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Stonemason', 'Dwarf', 'Hammer', 'Leather apron (as Hide armor)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Stonemason', 'Dwarf', 'Hammer', 'Leather apron (as Hide armor)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Tinker', 'Dwarf', 'Hammer', 'Copper kettle (as iron helmet)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Tunnelrunner', 'Dwarf', 'Short sword', 'Pair of well-made shoes', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Aethermancer', 'Elf', 'Staff', 'Aetherglass', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Actor', 'Elf', 'Longsword prop (as club)', 'Mirror', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Artisan', 'Elf', 'Hammer', 'Clay, 1 lb', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Astronomer', 'Elf', 'Staff', 'Spyglass', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Beekeeper', 'Elf', 'Spear', 'Jar of honey', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Courtier', 'Elf', 'Long knife (as dagger)', 'Mask', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Chandler', 'Elf', 'Scissors (as dagger)', 'Candles, 20', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Envoy', 'Elf', 'Staff of office (as club)', 'Butterfly collection pressed in book', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Falconer', 'Elf', 'Dagger', 'Falcon', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Forester', 'Elf', 'Bow', 'Leather helm', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Forester', 'Elf', 'Bow', 'Leather helm', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Glassblower', 'Elf', 'Hammer', 'Glass beads', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Herbalist', 'Elf', 'Staff', 'Herbs, 1 lb.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Mariner', 'Elf', 'Longsword', 'Water-repellant cloak', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Merchant', 'Elf', 'Dagger', 'Vial of rainbow dust', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Messenger', 'Elf', 'Dagger', 'Fine hat with peacock feather', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Musician', 'Elf', 'Musical instrument (as club)', 'Multi-colored cloak', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Navigator', 'Elf', 'Bow', 'Sextant', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Outcast', 'Elf', 'Staff', 'Pixie collection pressed in book', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Sage', 'Elf', 'Dagger', 'Parchment and quill pen', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Sculptor', 'Elf', 'Chisel (as dagger)', 'Small statue of unicorn', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Singer', 'Elf', 'Dagger', 'Fine cloak', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Spearwielder', 'Elf', 'Spear', 'Brass helm', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Treewarden', 'Elf', 'Staff', 'Leaf collection pressed in book', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Treewarden', 'Elf', 'Staff', 'Leaf collection pressed in book', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Vintner', 'Elf', 'Knife (as dagger)', 'Bottles of elven wine, 2', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Wayfarer', 'Elf', 'Longsword', 'Green cloak', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Waywatcher', 'Elf', 'Longsword', 'Horn', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Chicken butcher', 'Halfling', 'Hand axe', 'Plucked chicken', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Baker', 'Halfling', 'Rolling pin (as club)', 'Loaves of bread, 2', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Borderwarden', 'Halfling', 'Spear', 'Horn', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Brewer', 'Halfling', 'Wooden Mallet (as club)', 'Iron mug', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Burglar', 'Halfling', 'Dagger', 'Glass-cutter', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Cook', 'Halfling', 'Cleaver (as dagger)', 'Metal pot (used as iron helmet)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Cook', 'Halfling', 'Cleaver (as dagger)', 'Metal pot (used as iron helmet)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Dyer', 'Halfling', 'Staff', 'Fabric, 3 yards', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Farmer', 'Halfling', 'Pitchfork (as spear)', 'Hen**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Farmer', 'Halfling', 'Pitchfork (as spear)', 'Hen**', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Ferryman', 'Halfling', 'Staff', 'Wide-brimmed hat', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Gentleman', 'Halfling', 'Short sword', 'Fine outfit with brass buttons', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Glovemaker', 'Halfling', 'Awl (as dagger)', 'Gloves, 4 pairs', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Haberdasher', 'Halfling', 'Scissors (as dagger)', 'Fine suits, 3 sets', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Hunter', 'Halfling', 'Bow, short', 'Horn', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Keeper of the hounds', 'Halfling', 'Spear', 'Dog', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Messenger', 'Halfling', 'Dagger', 'Whistle', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Miller', 'Halfling', 'Wooden Mallet (as club)', 'Flour, 1 lb.', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Moneylender', 'Halfling', 'Dagger', 'Ledger', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Shire Reeve', 'Halfling', 'Short sword', 'Leather armor', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Trader', 'Halfling', 'Dagger', '20 sp', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Vagrant', 'Halfling', 'Club', 'Pipe and 3 oz. of pipeweed', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
      new ProfessionFull('Servingwench', 'Halfling', 'Knife (as dagger)', 'Serving Tray (as shield)', 'See Page 16', 'https://www.theoldsystem.com/forDownloads/Tabletops/Dungeon%20Crawl%20Classics%20RPG/Supplements/DCC%20-%20Alternate%20Occupations.pdf'),
    ];
  }

  public get medievalProfesions(): Profession[] {
    return [
      new Profession('Acrobat', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Apothecarist', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Architect', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Armorer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Artist', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Astrologer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Baker', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Barrister', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Bookbinder', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Bowyer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Brewer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Bricklayer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Candlemaker', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Carpenter', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Cartographer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Clothier', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Cook', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Diplomat', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Dyer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Engineer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Engraver', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Farmer', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Fisherman', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Forester', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Fortune-Teller', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Furrier', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Gardener', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Glassblower', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Grain Merchant', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Gravedigger', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Herald', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Herbalist', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Hunter', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Innkeeper', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Interpreter', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Jester', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Jeweler', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Leatherworker', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Locksmith', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Messenger', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Miner', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Minstrel', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Moneylender', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Navigator', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Painter', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Peddler', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Physician', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Playwright', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Politician', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Potter', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Rat Catcher', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Sailor', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Scribe', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Servant', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Shipwright', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Shoemaker', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Spy', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Stonecarver', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Storyteller', '', 'http://hkcarms.tripod.com/occ.html'),
      new Profession('Weaver', '', 'http://hkcarms.tripod.com/occ.html'),
    ];
  }

  public get dodgySciFiProfessions(): Profession[] {
    return [
      new Profession('High School Jock'),
      new Profession('Street Kid'),
      new Profession('Wealthy Upbringing'),
      new Profession('Noble'),
      new Profession('Bartender'),
      new Profession('Band Member'),
      new Profession('Record Contract'),
      new Profession('Street Thug'),
      new Profession('Gangster'),
      new Profession('Con Artist'),
      new Profession('Burglar'),
      new Profession('Prison'),
      new Profession('Sports Scholarship'),
      new Profession('Pro Athlete'),
      new Profession('Superstar Athlete'),
      new Profession('College'),
      new Profession('Advanced College'),
      new Profession('Doctorate'),
      new Profession('Field Scientist'),
      new Profession('Counsellor'),
      new Profession('Military Academy'),
      new Profession('Starfleet Cadet Cruise'),
      new Profession('Starfleet Tour'),
      new Profession('Starship Engineer'),
      new Profession('Starship Science Officer'),
      new Profession('Starship Communications Officer'),
      new Profession('Starship Counsellor'),
      new Profession('Starship Medical Officer'),
      new Profession('Starship Security Officer'),
      new Profession('Starship Helmsman'),
      new Profession('Academy Teaching'),
      new Profession('Starbase Assignment'),
      new Profession('Space Marines Cadet Assignment'),
      new Profession('Space Marines Tour of Duty'),
      new Profession('Starfleet Intelligence Recruit'),
      new Profession('Police Officer'),
      new Profession('Detective'),
      new Profession('Psi-Corps'),
      new Profession('Smuggler'),
      new Profession('Drifter'),
      new Profession('Gambler'),
      new Profession('Space Jockey'),
      new Profession('Priest'),
      new Profession('Scout / Explorer'),
      new Profession('Musician'),
      new Profession('Revolutionary'),
      new Profession('Asteroid Miner'),
      new Profession('Deepspace Construction'),
      new Profession('Roboticist'),
      new Profession('Cyberneticist'),
      new Profession('Geneticist'),
      new Profession('Clone'),
      new Profession('Creche-raised'),
      new Profession('Genetically Altered'),
      new Profession('Mutant'),
      new Profession('Heavy-Worlder'),
      new Profession('Radiation Scarred'),
      new Profession('Runaway Regeneration'),
      new Profession('Ship-bred'),
      new Profession('null-g habitat'),
      new Profession('Entertainer'),
      new Profession('Actor'),
      new Profession('Journalist'),
      new Profession('Programmer/Hacker'),
      new Profession('Physician'),
      new Profession('Nanotech/3D Printing Engineer'),
      new Profession('Body Guard/Security Expert'),
      new Profession('Fire Fighter'),
      new Profession('Hazardous Materials Handler'),
      new Profession('Ecologist/Planetologist/Climatologist/Terra-forming Engineer'),
      new Profession('Exo-Welder/Construction Worker'),
      new Profession('Drone Operator/Robot Supervisor'),
      new Profession('Professional Gamer'),
      new Profession('Professional Simulation Designer'),
      new Profession('CAD/CAM Draftsman'),
      new Profession('Holography Engineer'),
      new Profession('Archaeologist')
    ];
  }
}
